# Generated by Django 6.0.6 on 2026-06-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('orange', 'Naranja'), ('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarillo'), ('pink', 'Rosa'), ('amber', 'Ámbar'), ('purple', 'Morado'), ('red', 'Rojo')], default='orange', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='Landing.etiqueta'),
        ),
    ]
