# Generated by Django 6.0.6 on 2026-06-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0004_grupos_permisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
    ]
